name: Release Build
on:
  release:
    types:
      - released

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
    - name: Install dependencies
      run: make deps
    - name: Vet
      run: make vet
    - name: Static Check
      run: make staticcheck
    - name: Test
      run: make test
  
  build:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
    - name: Build binaries for multiple platforms
      run: |
        VERSION=${GITHUB_REF_NAME} make release-body
        mkdir -p bin
        GOOS=linux GOARCH=amd64 go build -o bin/santa-Linux-x86_64
        GOOS=linux GOARCH=386 go build -o bin/santa-Linux-i386
        GOOS=linux GOARCH=arm go build -o bin/santa-Linux-arm
        GOOS=linux GOARCH=arm GOARM=5 go build -o bin/santa-Linux-armv5l
        GOOS=linux GOARCH=arm GOARM=6 go build -o bin/santa-Linux-armv6l
        GOOS=linux GOARCH=arm GOARM=7 go build -o bin/santa-Linux-armv7l
        GOOS=linux GOARCH=arm64 go build -o bin/santa-Linux-armv8l
        GOOS=linux GOARCH=arm64 go build -o bin/santa-Linux-arm64
        GOOS=darwin GOARCH=amd64 go build -o bin/santa-Darwin-x86_64
        GOOS=darwin GOARCH=arm64 go build -o bin/santa-Darwin-arm64
        GOOS=windows GOARCH=amd64 go build -o bin/santa-Windows-amd64.exe
        GOOS=windows GOARCH=386 go build -o bin/santa-Windows-386.exe
        GOOS=windows GOARCH=arm64 go build -o bin/santa-Windows-arm64.exe
        GOOS=windows GOARCH=arm go build -o bin/santa-Windows-arm.exe
      env:
        CGO_ENABLED: 0
    - name: Upload binaries
      uses: softprops/action-gh-release@v2
      with:
        body_path: RELEASE.md
        files: bin/**/*
        token: ${{ secrets.GH_TOKEN }}

