name: Release Build
on:
  release:
    types:
      - released

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
    - name: Install dependencies
      run: make deps
    - name: Vet
      run: make vet
    - name: Static Check
      run: make staticcheck
    - name: Test
      run: make test
  
  build:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
    - name: Build binaries for multiple platforms
      run: |
        make release-body
        mkdir -p bin
        GOOS=linux GOARCH=amd64 go build -o bin/Linux/x86_64/santa
        GOOS=linux GOARCH=386 go build -o bin/Linux/i386/santa
        GOOS=linux GOARCH=arm go build -o bin/Linux/arm/santa
        GOOS=linux GOARCH=arm GOARM=5 go build -o bin/Linux/armv5l/santa
        GOOS=linux GOARCH=arm GOARM=6 go build -o bin/Linux/armv6l/santa
        GOOS=linux GOARCH=arm GOARM=7 go build -o bin/Linux/armv7l/santa
        GOOS=linux GOARCH=arm64 go build -o bin/Linux/armv8l/santa
        GOOS=linux GOARCH=arm64 go build -o bin/Linux/arm64/santa
        GOOS=darwin GOARCH=amd64 go build -o bin/Darwin/x86_64/santa
        GOOS=darwin GOARCH=arm64 go build -o bin/Darwin/arm64/santa
        GOOS=windows GOARCH=amd64 go build -o bin/Windows/amd64/santa.exe
        GOOS=windows GOARCH=386 go build -o bin/Windows/386/santa.exe
        GOOS=windows GOARCH=arm64 go build -o bin/Windows/arm64/santa.exe
        GOOS=windows GOARCH=arm go build -o bin/Windows/arm/santa.exe
      env:
        CGO_ENABLED: 0
    - name: Upload binaries
      uses: softprops/action-gh-release@v2
      with:
        body_path: RELEASE.MD
        files: bin/**/*
        token: ${{ secrets.GH_TOKEN }}

